apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: kotori-market
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: nginx:1.27-alpine
          ports:
            - containerPort: 8090
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: kotori-market
data:
  default.conf: |
    server {
        listen 8090;
        root /usr/share/nginx/html;
        index index.html;
        location / {
            try_files $uri $uri/ /index.html;
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: kotori-market
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 8090
      nodePort: 30090
