apiVersion: v2
name: kotori-market
description: Kotori Market microservices Helm chart
type: application
version: 0.1.0
appVersion: "latest"
keywords:
  - kotlin
  - spring-boot
  - microservices
maintainers:
  - name: kotori-market
