apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kotori-market
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kotlin-app/kotlin-infra.git
    targetRevision: main
    path: helm/kotori-market
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kotori-market
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
